### ISSUE TITLE
Please add SPLDoc

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.adaptiveParser#4]
The AdaptiveParser is very powerful.  However, because there is not documentation, it is very difficult to get started. 

As a first step, perhaps, we should add SPLDoc to parameters to functions, so users can figure out how to use these options.  Without a description, it's almost impossible to start.

Thanks!

**Comment by markheger** [comment]
SPLDoc is in iopages http://ibmstreams.github.io/streamsx.adaptiveParser/com.ibm.streamsx.adaptiveparser/doc/spldoc/html/index.html
