### ISSUE TITLE
Error about > 50 attributes

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.adaptiveParser#5]
I tried to parse a very complex structure with the adaptiveParser.

I got the following error when trying to compile the code:
 CDISP9164E ERROR: More than 50 attributes on the same level of tuple is not supported
CDISP0232E ERROR: An error was encountered during the generation of the code for the EHRStream operator.

Is there any reason why we have an upper limit of 50 attributes?  Do you have any recommendation on how to get around this?

Thanks!

**Comment by leongor** [comment]
Yes, the reason behind is that boost spirit qi library based on boost fusion library and it has such a limitation.
The workaround is very simple: when you have so many attributes on the same level of a tuple, they are usually can be grouped by different subjects. So, just divide the flat tuple to 2 or more tuples. If lists, sets or maps naturally fit they can be used too of course.
